database: h2

spring:
  datasource:
    initialize: true
    driver-class-name: org.h2.Driver
    url: 'jdbc:h2:mem:testdb;MODE=MySQL'
    username: sa
    password:
    data: classpath*:db/${database}/data.sql

  jpa:
    show_sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect

  h2:
    console:
      enabled: true
      path: '/h2-console'